"""add transcription session tables

Revision ID: 0838ab6e302a
Revises: 1bc7e1933749
Create Date: 2026-02-24 14:14:23.477755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0838ab6e302a'
down_revision: Union[str, Sequence[str], None] = '1bc7e1933749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker', sa.Integer(), nullable=False),
    sa.Column('timestamp_start', sa.Float(), nullable=False),
    sa.Column('timestamp_end', sa.Float(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['transcription_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['transcription_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'segment_index', name='uq_segments_session_index')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_event'))
        batch_op.drop_index(batch_op.f('idx_audit_vault'))

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chunks_bm25'), postgresql_with={'key_field': 'id'}, postgresql_using='bm25')
        batch_op.drop_index(batch_op.f('idx_chunks_doc'))
        batch_op.drop_index(batch_op.f('idx_chunks_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
        batch_op.drop_index(batch_op.f('idx_chunks_parent'))
        batch_op.drop_index(batch_op.f('idx_chunks_vault_active'), postgresql_where='(NOT is_deleted)')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_documents_hash'))
        batch_op.drop_index(batch_op.f('idx_documents_vault_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_documents_vault_status'), ['vault_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_documents_hash'), ['file_hash_sha256'], unique=False)

    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chunks_vault_active'), ['vault_id'], unique=False, postgresql_where='(NOT is_deleted)')
        batch_op.create_index(batch_op.f('idx_chunks_parent'), ['parent_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chunks_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
        batch_op.create_index(batch_op.f('idx_chunks_doc'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chunks_bm25'), ['id', 'content_with_header'], unique=False, postgresql_with={'key_field': 'id'}, postgresql_using='bm25')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_vault'), ['vault_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_event'), ['event_type', sa.literal_column('created_at DESC')], unique=False)

    op.drop_table('transcription_segments')
    op.drop_table('transcription_claims')
    op.drop_table('transcription_sessions')
    # ### end Alembic commands ###
