"""add_vaults_documents_chunks_audit_feedback_tables

Revision ID: 1bc7e1933749
Revises: 3c0f395bc482
Create Date: 2026-02-23 10:00:48.009353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '1bc7e1933749'
down_revision: Union[str, Sequence[str], None] = '3c0f395bc482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=True),
    sa.Column('doc_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_ir_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'file_hash_sha256', name='uq_documents_vault_hash')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_members',
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('vault_id', 'user_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('parent_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_with_header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('section_heading', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('section_level', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('chunk_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', 'chunk_version', name='uq_chunks_doc_index_version')
    )

    # -- Custom indexes (pgvector HNSW + pg_search BM25) --
    op.create_index('idx_chunks_vault_active', 'chunks', ['vault_id'], postgresql_where=sa.text('NOT is_deleted'))
    op.create_index('idx_chunks_doc', 'chunks', ['doc_id'])
    op.create_index('idx_chunks_parent', 'chunks', ['parent_chunk_id'])
    op.create_index('idx_documents_vault_status', 'documents', ['vault_id', 'status'])
    op.create_index('idx_documents_hash', 'documents', ['file_hash_sha256'])
    op.create_index('idx_audit_vault', 'audit_log', ['vault_id', sa.text('created_at DESC')])
    op.create_index('idx_audit_event', 'audit_log', ['event_type', sa.text('created_at DESC')])

    # HNSW index for dense vector search
    op.execute("""
        CREATE INDEX idx_chunks_embedding ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 200)
    """)

    # BM25 index for full-text search (pg_search)
    op.execute("""
        CREATE INDEX idx_chunks_bm25 ON chunks
        USING bm25 (id, content_with_header)
        WITH (key_field = 'id')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_bm25', table_name='chunks')
    op.drop_index('idx_chunks_embedding', table_name='chunks')
    op.drop_index('idx_audit_event', table_name='audit_log')
    op.drop_index('idx_audit_vault', table_name='audit_log')
    op.drop_index('idx_documents_hash', table_name='documents')
    op.drop_index('idx_documents_vault_status', table_name='documents')
    op.drop_index('idx_chunks_parent', table_name='chunks')
    op.drop_index('idx_chunks_doc', table_name='chunks')
    op.drop_index('idx_chunks_vault_active', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('vault_members')
    op.drop_table('feedback')
    op.drop_table('documents')
    op.drop_table('vaults')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
